app:
  port: 3000
  globalPrefix: ''
  NODE_ENV: development

logger:
  colorize: true
  defaultLevel: info
  prettyLogs: true

database:
  user: postgres
  password: postgres
  host: localhost
  port: 5438
  name: aiofc_db
